const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');

const source = fs.readFileSync('background/message-router.js', 'utf8');
const globalScope = {};
const api = new Function('self', `${source}; return self.MultiPageBackgroundMessageRouter;`)(globalScope);

test('message router clears account cost ledger without touching account run history', async () => {
  const events = {
    clearLedgerCalls: 0,
    clearHistoryCalls: 0,
  };

  const router = api.createMessageRouter({
    addLog: async () => {},
    appendAccountRunRecord: async () => null,
    batchUpdateLuckmailPurchases: async () => {},
    buildLocalhostCleanupPrefix: () => '',
    buildLuckmailSessionSettingsPayload: () => ({}),
    buildPersistentSettingsPayload: () => ({}),
    broadcastDataUpdate: () => {},
    cancelScheduledAutoRun: async () => {},
    checkIcloudSession: async () => {},
    clearAccountCostLedger: async () => {
      events.clearLedgerCalls += 1;
      return { clearedCount: 4 };
    },
    clearAccountRunHistory: async () => {
      events.clearHistoryCalls += 1;
      return { clearedCount: 2 };
    },
    deleteAccountRunHistoryRecords: async () => ({ deletedCount: 0, remainingCount: 0 }),
    clearAutoRunTimerAlarm: async () => {},
    clearLuckmailRuntimeState: async () => {},
    clearStopRequest: () => {},
    closeLocalhostCallbackTabs: async () => {},
    closeTabsByUrlPrefix: async () => {},
    completeStepFromBackground: async () => {},
    deleteHotmailAccount: async () => {},
    deleteHotmailAccounts: async () => {},
    deleteIcloudAlias: async () => {},
    deleteUsedIcloudAliases: async () => {},
    disableUsedLuckmailPurchases: async () => {},
    doesStepUseCompletionSignal: () => false,
    ensureMail2925MailboxSession: async () => {},
    ensureManualInteractionAllowed: async () => ({}),
    executeStep: async () => {},
    executeStepViaCompletionSignal: async () => {},
    exportSettingsBundle: async () => ({}),
    fetchGeneratedEmail: async () => '',
    fetchHotmail007Balance: async () => ({}),
    fetchHotmail007MailPriceList: async () => ({}),
    refreshGpcCardBalance: async () => ({}),
    finalizePhoneActivationAfterSuccessfulFlow: async () => {},
    finalizeStep3Completion: async () => {},
    finalizeIcloudAliasAfterSuccessfulFlow: async () => {},
    findHotmailAccount: async () => null,
    findPayPalAccount: async () => null,
    flushCommand: async () => {},
    getCurrentLuckmailPurchase: () => null,
    getCurrentPayPalAccount: () => null,
    getCurrentMail2925Account: () => null,
    getPendingAutoRunTimerPlan: () => null,
    getSourceLabel: () => '',
    getState: async () => ({ stepStatuses: { 1: 'pending' } }),
    getStepDefinitionForState: () => null,
    getStepIdsForState: () => [],
    getLastStepIdForState: () => 0,
    getTabId: async () => null,
    getStopRequested: () => false,
    handleAutoRunLoopUnhandledError: async () => {},
    importSettingsBundle: async () => {},
    invalidateDownstreamAfterStepRestart: async () => {},
    isCloudflareSecurityBlockedError: () => false,
    isAutoRunLockedState: () => false,
    isHotmailProvider: () => false,
    isLocalhostOAuthCallbackUrl: () => true,
    isLuckmailProvider: () => false,
    isStopError: () => false,
    isTabAlive: async () => false,
    launchAutoRunTimerPlan: async () => {},
    ensureIpProxyAutoSyncAlarm: async () => {},
    clearIpProxyAutoSyncAlarm: async () => {},
    runIpProxyAutoSync: async () => {},
    listIcloudAliases: async () => [],
    listLuckmailPurchasesForManagement: async () => [],
    markCurrentCustomEmailPoolEntryUsed: async () => {},
    markCurrentRegistrationAccountUsed: async () => {},
    normalizeHotmailAccounts: (items) => items,
    normalizeMail2925Accounts: (items) => items,
    normalizePayPalAccounts: (items) => items,
    normalizeRunCount: (value) => value,
    AUTO_RUN_TIMER_KIND_SCHEDULED_START: 'scheduled',
    notifyStepComplete: () => {},
    notifyStepError: () => {},
    patchMail2925Account: async () => {},
    patchHotmailAccount: async () => {},
    purchaseHotmailAccountFromHotmail007: async () => null,
    purchaseHotmailAccountsFromHotmail007: async () => ({}),
    pollContributionStatus: async () => ({}),
    registerTab: async () => {},
    requestStop: async () => {},
    probeIpProxyExit: async () => ({}),
    handleCloudflareSecurityBlocked: async () => {},
    resetState: async () => {},
    resumeAutoRun: async () => {},
    scheduleAutoRun: async () => {},
    selectLuckmailPurchase: async () => {},
    switchIpProxy: async () => {},
    changeIpProxyExit: async () => {},
    setCurrentPayPalAccount: async () => {},
    setCurrentMail2925Account: async () => {},
    setCurrentHotmailAccount: async () => {},
    setContributionMode: async () => {},
    setEmailState: async () => {},
    setEmailStateSilently: async () => {},
    setSignupPhoneState: async () => {},
    setSignupPhoneStateSilently: async () => {},
    setIcloudAliasPreservedState: async () => {},
    setIcloudAliasUsedState: async () => {},
    setLuckmailPurchaseDisabledState: async () => {},
    setLuckmailPurchasePreservedState: async () => {},
    setLuckmailPurchaseUsedState: async () => {},
    setPersistentSettings: async () => {},
    setState: async () => {},
    setStepStatus: async () => {},
    skipAutoRunCountdown: async () => false,
    skipStep: async () => {},
    startContributionFlow: async () => ({}),
    startAutoRunLoop: async () => {},
    deleteMail2925Account: async () => {},
    deleteMail2925Accounts: async () => {},
    syncHotmailAccounts: async () => {},
    syncPayPalAccounts: async () => {},
    testHotmailAccountMailAccess: async () => {},
    upsertPayPalAccount: async () => {},
    upsertMail2925Account: async () => {},
    upsertHotmailAccount: async () => {},
    verifyHotmailAccount: async () => {},
  });

  const response = await router.handleMessage({
    type: 'CLEAR_ACCOUNT_COST_LEDGER',
    source: 'sidepanel',
  }, {});

  assert.deepStrictEqual(response, { ok: true, clearedCount: 4 });
  assert.equal(events.clearLedgerCalls, 1);
  assert.equal(events.clearHistoryCalls, 0);
});
